import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import NextTopLoader from "nextjs-toploader";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  const isSession = !!session;
  // connectToDatabase();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <NextTopLoader showSpinner={false} />
          <Navbar session={session} />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
